function Start(){
//   let ans1 = window.prompt("enter number 1")

//    let ans2 = window.prompt("enter number 2")

// let ans3 = window.alert(parseInt(ans1) + parseInt(ans2))

// let ans = window.confirm("are satisfied wit this website")
// if(ans==true){
//     alert("thanku")
// }else{
//     alert("sorry")
// }

   
    //  let ans = confirm("are u satisfied with our website")
    //  if(ans==true){
    //     alert("thanku")

    //  }else{
    //     alert("sorry")
    //  }
    // alert("welcome to our website")

   let show1 = window.prompt("enter the 1st number")
    let show2 = window.prompt("neter the 2nd number")
    alert(parseInt(show1) + parseInt(show2))


}
Start();
  